[package]
name = "lucid_kacker_type"
version = "0.1.0"
authors = [
    "Alienduck"
]
edition = "2024"
description = "A simple tool for hacker typing everywhere"
repository = "https://github.com/Alienduck/LucidHackType"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
enigo = "0.6.1"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
